### ISSUE TITLE
Async mode ?

### ISSUE THREAD

**Issue by mildred** [zendbit/nim.zfblast#3]
I need to start two servers at the same time to listen on different ports, and I wanted to suggest you make public the `doServe` and `doServeSecure` so we can have control of the main loop.

It seems that the README advertises async mode with the snippet:

```nim
waitfor zfb.serve(proc (ctx: HttpContext): Future[void] {.async.} =
```

But not the code (the serve proc is not returning a Future):

https://github.com/zendbit/nim.zfblast/blob/23247b371f49af6388da3c4b4059f9512827e799/src/zfblast.nim#L586-L596

**Comment by zendbit** [comment]
Hello can you check the latest, I already enable the asyncdispatch also make doServe and doServeSecure as public

you can install with latest head, because on the nimble dir not synced:
```
nimble install zfblast#head
```
Thanks mate.

**Comment by mildred** [comment]
Thank you
